# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf873c746de81efed92b6867cf64dda36a318259f47e11eb26bd7e3b6f2655fea38010ceac63dd3dc4fcf9f5b368b52cac47f042d876a20ce7bf6b4630c4667a

test:
  secret_key_base: abd6e5ef125466f91ec6ec94c382f66c22de7d7727cccb76027704143df66a459f19507056aa67b78db826b47392acf8c52d106a3e78e4f2635a50f0c21f085c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
